django_playground/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
from animalia import admin
#admin.autodiscover()

handler404 = 'movie_library.views.my_404_view'
handler500 = 'movie_library.views.my_500_view'
handler403 = 'movie_library.views.my_403_view'
handler400 = 'movie_library.views.my_500_view'

urlpatterns = patterns('',
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    # url(r'^about/$',
    #     TemplateView.as_view(template_name='pages/about.html'),
    #     name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),
    url(r'^animalia/', include('animalia.urls')),
    url(r'^movies/', include('movie_library.urls')),

    # Your stuff: custom urls go here

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
    # static files (images, css, javascript, etc.)
urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

django_playground/movie_library/urls.py
__author__ = 'Timo'

from django.conf.urls import patterns, include, url
from django.contrib import admin
from views import MovieDetail

urlpatterns = patterns('',

    url(r'^$', 'movie_library.views.home', name='home'),
    url(r'^list$', 'movie_library.views.movie_list'),
    url(r'^id/(?P<pk>[-_\w]+)/$', MovieDetail.as_view()),
    url(r'^directors$', 'movie_library.views.movie_directors'),
    (r'^dashboard/$', 'movie_library.views.dashboard'),
    (r'^dashboard/add/movie$', 'movie_library.views.dashboard_add_movie'),
    (r'^dashboard/add/director$', 'movie_library.views.dashboard_add_director'),
    (r'^dashboard/add/writer$', 'movie_library.views.dashboard_add_writer'),
    (r'^dashboard/add/actor$', 'movie_library.views.dashboard_add_actor'),
    (r'^dashboard/add/genre$', 'movie_library.views.dashboard_add_genre'),
)

django_playground/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w\-_]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

django_playground/movie_library/models.py
from django.db import models
from users.models import User

# Create your models here.
class Studio(models.Model):
    name = models.CharField(max_length=30)
    address = models.TextField(blank=True)
    city = models.CharField(max_length=100, blank=True)
    state_province = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    website = models.URLField(blank=True)
    def __unicode__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=50)
    explanation = models.TextField(blank=True)
    def __unicode__(self):
        return self.name

class Writer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    def __unicode__(self):
        return self.first_name+" "+self.last_name

class Actor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    head_shot = models.ImageField(upload_to='head_shot/actors', blank=True)
    def __unicode__(self):
        return self.first_name+" "+self.last_name

class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    nick_name = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        return self.first_name+" "+self.last_name

class Rating(models.Model):
    name = models.CharField(max_length=100)
    explanation = models.TextField(blank=True)
    def __unicode__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    writer = models.ManyToManyField(Writer)
    actor = models.ManyToManyField(Actor)
    director = models.ManyToManyField(Director)
    genre = models.ManyToManyField(Genre, blank=True, null=True)
    trailer = models.URLField(blank=True)
    synopsis = models.TextField(blank=True)
    studio = models.ForeignKey(Studio, blank=True, null=True)
    release_year = models.IntegerField(blank=True)
    cover_art = models.ImageField(upload_to='cover_art')
    is_featured = models.BooleanField(default=False)
    rating = models.ForeignKey(Rating, blank=True, null=True)
    uploaded_by = models.ForeignKey(User)
    def __unicode__(self):
        return self.title

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')
    caption = models.TextField(blank=True)
    movie = models.ForeignKey(Movie)
    def __unicode__(self):
        return self.image.name

django_playground/movie_library/forms.py
__author__ = 'Timo'
from django import forms
from models import Movie, Director, Studio, Writer, Actor, Genre, Rating
import django_filters
from django_filters.widgets import LinkWidget

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        exclude = ('uploaded_by',)

class WriterForm(forms.ModelForm):
    class Meta:
        model = Writer

class DirectorForm(forms.ModelForm):
    class Meta:
        model = Director

class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor

class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre

class MovieFilter(django_filters.FilterSet):
    genre = django_filters.ModelChoiceFilter(queryset=Genre.objects.all(), widget=LinkWidget)
    director = django_filters.ModelChoiceFilter(queryset=Director.objects.all(), widget=LinkWidget)
    actor = django_filters.ModelChoiceFilter(queryset=Actor.objects.all(), widget=LinkWidget)
    rating = django_filters.ModelChoiceFilter(queryset=Rating.objects.all(), widget=LinkWidget)
    writer = django_filters.ModelChoiceFilter(queryset=Writer.objects.all(), widget=LinkWidget)
    studio = django_filters.ModelChoiceFilter(queryset=Studio.objects.all(), widget=LinkWidget)
    class Meta:
        model = Movie
        fields = ['genre', 'director', 'actor', 'writer', 'rating', 'studio']

django_playground/movie_library/views.py
from django.shortcuts import render_to_response
from models import Movie
from django.views.generic import DetailView
from django.http import Http404
from django.db.models import F
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from forms import MovieForm, ActorForm, GenreForm, DirectorForm, WriterForm, MovieFilter

def home(request):
    movies_list = Movie.objects.filter(is_featured=True)
    paginator = Paginator(movies_list, 6)
    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        movies = paginator.page(1)
    except EmptyPage:
        movies = paginator.page(paginator.num_pages)
    return render_to_response('movie_library/home.html', {'home_active':'active', 'movies': movies}, RequestContext(request))

def movie_list(request):
    f = MovieFilter(request.GET, queryset=Movie.objects.all())
    return render_to_response('movie_library/movie_list.html', {'movies_active':'active', 'filter':f})

def movie_directors(request):
    #directors = Director
    return render_to_response('movie_library/directors.html', {'directors_active':'active'})

class MovieDetail(DetailView):
    model = Movie
    template_name = 'movie_library/movie_detail.html'
    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        try:
            Movie.objects.filter(pk=pk)
            return Movie.objects.get(pk=pk)
        except Movie.DoesNotExist:
            raise Http404
def my_404_view(request):
    return render_to_response('movie_library/404.html', {}, RequestContext(request))

def my_403_view(request):
    return render_to_response('movie_library/403.html', {}, RequestContext(request))

def my_500_view(request):
    return render_to_response('movie_library/500.html', {}, RequestContext(request))

@login_required
def dashboard(request):
    context = RequestContext(request)
    movies = Movie.objects.filter(uploaded_by=request.user)
    #movie_form = ProductForm()
    return render_to_response("movie_library/dashboard/dashboard.html", {'movies': movies, "movie_form": '', 'dashboard_active':'active'}, context)

@login_required
def dashboard_add_movie(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.uploaded_by = request.user
            obj.save()
            return HttpResponseRedirect('/movies/dashboard')
        return render_to_response("movie_library/dashboard/add_movie.html", {"form": form, 'dashboard_active':'active'}, context)

    elif request.method == 'GET':
        form = MovieForm()
        return render_to_response("movie_library/dashboard/add_movie.html", {"form": form, 'dashboard_active':'active'}, context)

@login_required
def dashboard_add_actor(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = ActorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/movies/dashboard')
        return render_to_response("movie_library/dashboard/add_actor.html", {"form": form, 'dashboard_active':'active'}, context)

    elif request.method == 'GET':
        form = ActorForm()
        return render_to_response("movie_library/dashboard/add_actor.html", {"form": form, 'dashboard_active':'active'}, context)

@login_required
def dashboard_add_director(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = DirectorForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/movies/dashboard')
        return render_to_response("movie_library/dashboard/add_director.html", {"form": form, 'dashboard_active':'active'}, context)

    elif request.method == 'GET':
        form = DirectorForm()
        return render_to_response("movie_library/dashboard/add_director.html", {"form": form, 'dashboard_active':'active'}, context)

@login_required
def dashboard_add_writer(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = WriterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/movies/dashboard')
        return render_to_response("movie_library/dashboard/add_writer.html", {"form": form, 'dashboard_active':'active'}, context)

    elif request.method == 'GET':
        form = WriterForm()
        return render_to_response("movie_library/dashboard/add_writer.html", {"form": form, 'dashboard_active':'active'}, context)

@login_required
def dashboard_add_genre(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/movies/dashboard')
        return render_to_response("movie_library/dashboard/add_genre.html", {"form": form, 'dashboard_active':'active'}, context)

    elif request.method == 'GET':
        form = GenreForm()
        return render_to_response("movie_library/dashboard/add_genre.html", {"form": form, 'dashboard_active':'active'}, context)

django_playground/templates/movie_library/base.html
{% load staticfiles i18n %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
         <title>{%block title%}tmDB{% endblock %}</title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/icomoon-social.css' %}" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

        <link href="{% static 'css/leaflet.css' %}" rel="stylesheet">
		<!--[if lte IE 8]>
        <link href="{% static 'css/leaflet.ie.css' %}" rel="stylesheet">
		<![endif]-->
        <link href="{% static 'css/main-green.css' %}" rel="stylesheet">

        <script src="{% static 'js/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
        

        <!-- Navigation & Logo-->
        <div class="mainmenu-wrapper">
	        <div class="container">
	        	<!--<div class="menuextras">-->
					<!--<div class="extras">-->
						<!--<ul>-->
							<!--<li class="shopping-cart-items"><i class="glyphicon glyphicon-shopping-cart icon-white"></i> <a href="page-shopping-cart.html"><b>3 items</b></a></li>-->
							<!--<li>-->
								<!--<div class="dropdown choose-country">-->
									<!--<a class="#" data-toggle="dropdown" href="#"><img src="img/flags/gb.png" alt="Great Britain"> UK</a>-->
									<!--<ul class="dropdown-menu" role="menu">-->
										<!--<li role="menuitem"><a href="#"><img src="img/flags/us.png" alt="United States"> US</a></li>-->
										<!--<li role="menuitem"><a href="#"><img src="img/flags/de.png" alt="Germany"> DE</a></li>-->
										<!--<li role="menuitem"><a href="#"><img src="img/flags/es.png" alt="Spain"> ES</a></li>-->
									<!--</ul>-->
								<!--</div>-->
							<!--</li>-->
			        		<!--<li><a href="page-login.html">Login</a></li>-->
			        	<!--</ul>-->
					<!--</div>-->
		        <!--</div>-->
		        <nav id="mainmenu" class="mainmenu">
					<ul>
						<li class="logo-wrapper"><a href="/movies"><img src="img/mPurpose-logo.png" alt="tmDB"></a></li>
						<li class="{{home_active}}">
							<a href="/movies">Home</a>
						</li>
						<li class="{{movies_active}}">
							<a href="/movies/list">Movies</a>
						</li>
                        <!--<li class="{{directors_active}}">-->
							<!--<a href="movies/directors">Directors</a>-->
						<!--</li>-->
                        <!--<li class="{{actors_active}}">-->
							<!--<a href="/movies/actors">Actors</a>-->
						<!--</li>-->
                        {% if request.user.is_authenticated %}
                        <!--<li class="{{logout_active}}"><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>-->
                        <li class="{{dashboard_active}}"><a href="/movies/dashboard">Dashboard</a></li>
                        <li class="{{my_profile_active}}"><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
            <li class="{{logout_active}}"><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li class="{{signup_active}}"><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li class="{{login_active}}"><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
          {% endif %}
					</ul>
				</nav>
			</div>
		</div>

        {% block content %}
        {% endblock%}

	    <!-- Footer -->
	    <div class="footer">
	    	<div class="container">
		    	<div class="row">

		    		<div class="col-footer col-md-3 col-xs-6">
		    			<h3>Navigate</h3>
		    			<ul class="no-list-style footer-navigate-section">
		    				<li><a href="/movies">Home</a></li>
		    				<!--<li><a href="/movies/featured">Featured</a></li>-->
		    				<!--<li><a href="/movies/directors">Directors</a></li>-->
		    				<li><a href="/movies/list">All Movies</a></li>
		    				<!--<li><a href="/movies/pricing">Pricing</a></li>-->
		    				<!--<li><a href="/movies/faq">FAQ</a></li>-->
		    			</ul>
		    		</div>
		    		
		    		<div class="col-footer col-md-4 col-xs-6">
		    			<h3>Contacts</h3>
		    			<p class="contact-us-details">
	        				<b>Address:</b> RM B3-28 Anx, Lumumba Hall, Makerere University<br/>
	        				<b>Phone:</b> +256 779 685241<br/>
	        				<b>Email:</b> <a href="mailto:getintoutch@yourcompanydomain.com">hello@timothyasiimwe.me</a>
	        			</p>
		    		</div>
		    		<div class="col-footer col-md-2 col-xs-6">
		    			<h3>Stay Connected</h3>
		    			<ul class="footer-stay-connected no-list-style">
		    				<li><a href="https://www.facebook.com/timasiimwe" class="facebook"></a></li>
		    				<li><a href="https://twitter.com/TimAsiimwe" class="twitter"></a></li>
		    				<li><a href="https://plus.google.com/107976877056291197000" class="googleplus"></a></li>
		    			</ul>
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col-md-12">
		    			<div class="footer-copyright">&copy; 2014 Timothy Asiimwe. All rights reserved.</div>
		    		</div>
		    	</div>
		    </div>
	    </div>

        <!-- Javascripts -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/static/js/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="/static/js/bootstrap.min.js"></script>
        <script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
        <script src="/static/js/jquery.fitvids.js"></script>
        <script src="/static/js/jquery.sequence-min.js"></script>
        <script src="/static/js/jquery.bxslider.js"></script>
        <script src="/static/js/main-menu.js"></script>
        <script src="/static/js/template.js"></script>

    </body>
</html>

django_playground/templates/movie_library/home.html
{% extends "movie_library/base.html" %}
        {% block title%}tmDB - Featured Movies{% endblock%}
        {% block content %}
<!-- Page Title -->
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Featured Movies</h1>
					</div>
				</div>
			</div>
		</div>
        
        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="products-slider">
                            {% for movie in movies%}
                            <div class="shop-item">
								<!-- Product Image -->
								<div class="image">
									<a href="/movies/id/{{movie.id}}"><img src="{{movie.cover_art.url}}" alt="{{movie.title}}"></a>
								</div>
								<!-- Product Title -->
								<div class="title">
									<h3><a href="/movies/id/{{movie.id}}">{{movie.title}}</a></h3>
								</div>
								<!-- Product Price -->
								<!--<div class="price">-->
									<!--$999.99-->
								<!--</div>-->
								<!-- Buy Button -->
								<!--<div class="actions">-->
									<!--<a href="page-product-details.html" class="btn btn-small"><i class="icon-shopping-cart icon-white"></i> Buy</a>-->
								<!--</div>-->
							</div>
                            {% endfor %}
						</div>
					</div>
				</div>
			</div>
	    </div>
        {% endblock %}

django_playground/templates/movie_library/movie_detail.html
{% extends "movie_library/base.html" %}
        {% load staticfiles i18n %}
{% block title%}tmDB - {{object.title}}{% endblock%}
{% block content %}
        <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="{% static 'css/bootstrap-image-gallery.min.css' %}">
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{object.title}}</h1>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="row">
            <!-- Product Image & Available Colors -->
            <!--<div class="col-sm-6">-->
                <!--<div class="product-image-large">-->
                    <!--<img src="{{object.cover_art.url}}" alt="{{object.title}}">-->
                <!--</div>-->
            <!--</div>-->
                <div class="col-sm-6">
                    <h4>Trailer</h4>
						<div class="video-wrapper">
                             <!--<iframe-->
<!--src="http://www.youtube.com/embed/XGSy3_Czz8k">-->
<!--</iframe>-->
							<iframe src="{{object.trailer}}" width="554" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
						</div>
					</div>

            <!-- End Product Image & Available Colors -->
            <!-- Product Summary & Options -->
            <div class="col-sm-6 product-details">
                <h4>{{object.title}}</h4>
                {%for g in object.genre.all%}
                <div class="price">
                    <span class="">{{g.name}}</span>
                </div>
                {% endfor %}

                <h5>Directors</h5>

                <p>{{object.director_set.all.0}}</p>
                {% for d in object.director.all %}
                <span><a href="/movies/directors/id/{{id}}">{{d}}</a> </span>
                {% endfor %}
                <h5>Writers</h5>

                <p>{{object.writer_set.all.0}}</p>
                {% for w in object.writer.all %}
                <span><a href="/movies/writers/id/{{id}}">{{w}}</a> </span>
                {% endfor %}
                {% if object.studio%}
                <h5>Studio</h5>
                <span>{{object.studio}}</span>
                {% endif %}
                <h5>Gallery</h5>
                <div class="row">


                    <div id="links">
                        {%for p in object.photo_set.all%}
                        <div class="col-md-2 col-sm-3">
                            <div class="portfolio-item">
                                <div class="portfolio-image">
                                    <a href="{{p.image.url}}" title="{{p.caption}}" data-gallery>
                                        <img src="{{p.image.url}}" alt="{{p.caption}}" style="">
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>

            </div>
            <!-- End Product Summary & Options -->

            <!-- Full Description & Specification -->
            <div class="col-sm-12">
                <div class="tabbable">
                    <!-- Tabs -->
                    <ul class="nav nav-tabs product-details-nav">
                        <li class="active"><a href="#tab1" data-toggle="tab">Synopsis</a></li>
                        <li><a href="#tab2" data-toggle="tab">Cast</a></li>
                    </ul>
                    <!-- Tab Content (Full Description) -->
                    <div class="tab-content product-detail-info">
                        <div class="tab-pane active" id="tab1">
                            <h4>Synopsis</h4>

                            <p>{{object.synopsis}}</p>
                        </div>
                        <!-- Tab Content (Specification) -->
                        <div class="tab-pane" id="tab2">
                            {% for a in object.actor.all%}
                            <p>{{a}}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Full Description & Specification -->
        </div>
    </div>
</div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="{% static 'js/bootstrap-image-gallery.min.js' %}"></script>
{% endblock content%}

django_playground/templates/movie_library/movie_list.html
  {% extends "movie_library/base.html" %}
          {% load bootstrap%}
        {% block title%}tmDB - Featured Movies{% endblock%}
        {% block content %}
<!-- Page Title -->
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>All Movies</h1>
					</div>
				</div>
			</div>
		</div>

<div class="eshop-section section">
	    	<div class="container">
	    		<!--<h2>Listing With No Colors Information</h2>-->

				<div class="row">
                    <div class="col-md-2">
                        <p><b>Advanced Filter</b></p>
                        <p>Genre</p>
                        {{filter.form.genre}}
                        <p>Director</p>
                        {{filter.form.director}}
                        <p>Writer</p>
                        {{filter.form.writer}}
                        <p>Studio</p>
                        {{filter.form.studio}}
                        <p>Actors/Actresses</p>
                        {{filter.form.actor}}
                        <p>Rating</p>
                        {{filter.form.rating}}
                    </div>
                    <div class="col-md-10">
                    {% for m in filter %}
                    <div class="col-sm-4">
						<div class="shop-item">
							<div class="image">
								<a href="/movies/id/{{m.id}}"><img src="{{m.cover_art.url}}" alt="{{m.title}}"></a>
							</div>
							<div class="title">
								<h3><a href="/movies/id/{{m.id}}">{{m.title}}</a></h3>
							</div>
							<div class="description">
								<p>{{m.synopsis | truncatechars:100}}</p>
							</div>
						</div>
					</div>
                    {% endfor %}
                        </div>
				</div>
				<!--<div class="pagination-wrapper ">-->
					<!--<ul class="pagination pagination-lg">-->
						<!--<li class="disabled"><a href="#">Previous</a></li>-->
						<!--<li class="active"><a href="#">1</a></li>-->
						<!--<li><a href="#">2</a></li>-->
						<!--<li><a href="#">3</a></li>-->
						<!--<li><a href="#">4</a></li>-->
						<!--<li><a href="#">5</a></li>-->
						<!--<li><a href="#">6</a></li>-->
						<!--<li><a href="#">7</a></li>-->
						<!--<li><a href="#">8</a></li>-->
						<!--<li><a href="#">9</a></li>-->
						<!--<li><a href="#">10</a></li>-->
						<!--<li><a href="#">Next</a></li>-->
					<!--</ul>-->
				<!--</div>-->
			</div>
	    </div>
          {% endblock %}